MOCK_SHOPS = [
    {
        "name": "Bucharest Cotton Wear",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["cotton"],
        "colors": ["orange", "red", "blue"],
        "price": 110,
        "locality": "Bucharest",
        "url": "https://bucharestcottonwear.ro/tshirt1",
        "brand": "CottonWear",
        "description": "T-shirt 100% bumbac, produs local.",
        "rating": 4.7,
        "stock": 42,
        "employees": 28,
        "turnover": 450000,
        "cui": "12345678"
    },
    {
        "name": "Polyester Brothers",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["polyester"],
        "colors": ["orange", "red", "blue"],
        "price": 80,
        "locality": "Bucharest",
        "url": "https://polyesterbrothers.ro/tshirt1",
        "brand": "PolyBro",
        "description": "T-shirt poliester ușor și durabil.",
        "rating": 4.2,
        "stock": 66,
        "employees": 112,       # over 100 as requested
        "turnover": 1200000,
        "cui": "87654321"
    },
    {
        "name": "Luca Bakery",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 20,
        "locality": "Bucharest",
        "url": "https://luca-bakery.ro/sourdough",
        "brand": "Luca",
        "description": "Pâine cu maia, coaptă zilnic.",
        "rating": 4.8,
        "stock": 120,
        "employees": 250,        # large business
        "turnover": 5400000,
        "cui": "55334422"
    },
    {
        "name": "Sibiu Organic Bakery",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 25,
        "locality": "Sibiu",
        "url": "https://sibiu-bakery.ro/sourdough1",
        "brand": "SibiuBio",
        "description": "Pâine organică cu maia din Sibiu.",
        "rating": 4.9,
        "stock": 55,
        "employees": 18,
        "turnover": 190000,
        "cui": "99887766"
    },
    {
        "name": "Cluj Handmade Apparel",
        "category": "clothing",
        "item": "hoodie",
        "materials": ["cotton", "linen"],
        "colors": ["black", "white"],
        "price": 220,
        "locality": "Cluj",
        "url": "https://clujhandmade.ro/hoodie",
        "brand": "HandmadeCluj",
        "description": "Hanorac cusut manual din bumbac și in.",
        "rating": 4.6,
        "stock": 28,
        "employees": 12,
        "turnover": 80000,
        "cui": "44556677"
    },
    {
        "name": "Iași Eco Fashion",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["cotton", "recycled"],
        "colors": ["green", "white"],
        "price": 130,
        "locality": "Iasi",
        "url": "https://iasi-ecofashion.ro/tshirt",
        "brand": "EcoIasi",
        "description": "Tricou eco 50% reciclat.",
        "rating": 4.8,
        "stock": 35,
        "employees": 45,
        "turnover": 330000,
        "cui": "33445566"
    },
    {
        "name": "Timisoara Wool Studio",
        "category": "clothing",
        "item": "jacket",
        "materials": ["wool"],
        "colors": ["black", "grey"],
        "price": 350,
        "locality": "Timisoara",
        "url": "https://timisoara-wool.ro/jacket",
        "brand": "WoolTim",
        "description": "Jachetă din lână naturală.",
        "rating": 4.9,
        "stock": 15,
        "employees": 9,
        "turnover": 120000,
        "cui": "22334455"
    },
    {
        "name": "Brasov Artisan Knit",
        "category": "clothing",
        "item": "hoodie",
        "materials": ["wool"],
        "colors": ["blue", "grey"],
        "price": 260,
        "locality": "Brasov",
        "url": "https://brasovknit.ro/hoodie",
        "brand": "KnitBrasov",
        "description": "Hanorac împletit manual.",
        "rating": 4.5,
        "stock": 23,
        "employees": 15,
        "turnover": 140000,
        "cui": "11223344"
    },
    {
        "name": "Cluj Sourdough Masters",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 28,
        "locality": "Cluj",
        "url": "https://clujsourdough.ro/bread",
        "brand": "ClujMaia",
        "description": "Pâine artizanală cu maia.",
        "rating": 4.9,
        "stock": 48,
        "employees": 62,
        "turnover": 670000,
        "cui": "55667788"
    },
    {
        "name": "Timisoara Vegan Bites",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 22,
        "locality": "Timisoara",
        "url": "https://timi-vegan.ro/bread",
        "brand": "VeganTM",
        "description": "Pâine vegană cu semințe.",
        "rating": 4.7,
        "stock": 60,
        "employees": 21,
        "turnover": 230000,
        "cui": "66778899"
    },
    {
        "name": "Bucharest Eco Textiles",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["linen", "cotton"],
        "colors": ["white", "beige"],
        "price": 150,
        "locality": "Bucharest",
        "url": "https://eco-textiles.ro/tshirt",
        "brand": "EcoTex",
        "description": "Tricouri premium din materiale naturale.",
        "rating": 4.9,
        "stock": 39,
        "employees": 140,       # over 100
        "turnover": 2100000,
        "cui": "77889900"
    },
    {
        "name": "Oradea Handmade Leather",
        "category": "clothing",
        "item": "jacket",
        "materials": ["leather"],
        "colors": ["brown", "black"],
        "price": 450,
        "locality": "Oradea",
        "url": "https://oradealeather.ro/jacket",
        "brand": "LeatherOradea",
        "description": "Jachetă piele lucrată manual.",
        "rating": 4.6,
        "stock": 12,
        "employees": 8,
        "turnover": 90000,
        "cui": "88990011"
    },
    {
        "name": "Constanta Organic Bread Co",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 26,
        "locality": "Constanta",
        "url": "https://constanta-bio.ro/bread",
        "brand": "BioSea",
        "description": "Pâine organică cu semințe.",
        "rating": 4.8,
        "stock": 77,
        "employees": 37,
        "turnover": 410000,
        "cui": "99112233"
    },
    {
        "name": "Cluj Denim House",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["cotton", "denim"],
        "colors": ["blue"],
        "price": 140,
        "locality": "Cluj",
        "url": "https://clujdenim.ro/tshirt",
        "brand": "DenimCluj",
        "description": "Tricouri cu inserții denim.",
        "rating": 4.4,
        "stock": 30,
        "employees": 19,
        "turnover": 155000,
        "cui": "11220033"
    },
    {
        "name": "Craiova Artisan Bread",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 18,
        "locality": "Craiova",
        "url": "https://craiovabread.ro",
        "brand": "CrBread",
        "description": "Pâine tradițională românească.",
        "rating": 4.6,
        "stock": 84,
        "employees": 52,
        "turnover": 320000,
        "cui": "22112233"
    },
    {
        "name": "Timisoara Craft Clothes",
        "category": "clothing",
        "item": "hoodie",
        "materials": ["cotton"],
        "colors": ["orange", "black"],
        "price": 195,
        "locality": "Timisoara",
        "url": "https://tmcraft.ro/hoodie",
        "brand": "TMCraft",
        "description": "Hanorace premium făcute local.",
        "rating": 4.7,
        "stock": 26,
        "employees": 33,
        "turnover": 280000,
        "cui": "77112233"
    },
    {
        "name": "Braila Fresh Crust",
        "category": "food",
        "item": "bread",
        "materials": None,
        "colors": None,
        "price": 17,
        "locality": "Braila",
        "url": "https://brailabread.ro",
        "brand": "FreshCrust",
        "description": "Pâine proaspătă coaptă zilnic.",
        "rating": 4.5,
        "stock": 52,
        "employees": 14,
        "turnover": 110000,
        "cui": "66112233"
    },
    {
        "name": "Suceava Rustic Apparel",
        "category": "clothing",
        "item": "jacket",
        "materials": ["wool"],
        "colors": ["grey"],
        "price": 320,
        "locality": "Suceava",
        "url": "https://suceavaapparel.ro/jacket",
        "brand": "RusticSV",
        "description": "Jachetă rustică din lână românească.",
        "rating": 4.8,
        "stock": 14,
        "employees": 16,
        "turnover": 175000,
        "cui": "55112233"
    },
    {
        "name": "Pitesti Linen Studio",
        "category": "clothing",
        "item": "t-shirt",
        "materials": ["linen"],
        "colors": ["white", "beige"],
        "price": 160,
        "locality": "Pitesti",
        "url": "https://linenpitesti.ro/tshirt",
        "brand": "LinenPit",
        "description": "Tricouri din in natural.",
        "rating": 4.6,
        "stock": 31,
        "employees": 11,
        "turnover": 130000,
        "cui": "44112233"
    }
]

test_input = {
        "user_text": "I want a 100% cotton orange t-shirt from Bucharest"
}